name: AWS OIDC Test

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  aws-access:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC
      contents: read   # Access repository contents

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::329599620438:role/AWS-OIDC-Test
        aws-region: us-east-1  # Specify your AWS region

    - name: List S3 buckets (or any other AWS command)
      run: aws s3 ls
